pyweb/urls.py
from django.views.static import serve
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path
from app01.views import depart, pretty, user, admin, account, task, index, order, chart, upload
# from django.views.generic import TemplateView

urlpatterns = [
    # path("admin/", admin.site.urls),
    # path(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),

    # media 目录    [re_path: 一个正则表达式]
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # 首页
    path('', index.index),

    # 部门
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),
    path('depart/multi/', depart.depart_multi),

    # 用户
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    # 手机号
    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),

    # 管理员
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),


    # 登录
    path('login/', account.login),
    # 注销
    path('logout/', account.logout),
    # 图片验证码
    path('img/code/', account.img_code),


    # 任务管理
    path('task/list/', task.task_list),
    path('task/add/', task.task_add),
    path('task/<int:nid>/delete/', task.task_delete),

    # 订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/detail/', order.order_detail),
    path('order/delete/', order.order_delete),
    path('order/edit/', order.order_edit),

    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),
    path('chart/line/', chart.chart_line),

    # 上传文件
    path('upload/list/', upload.upload_list),
    path('upload/form/', upload.upload_form),
    path('upload/model/form/', upload.upload_model_form),
    path('city/list/', upload.city_list),
    path('city/add/', upload.city_add),

]

app01/models.py
from django.db import models

class Admin(models.Model):
    """管理员"""
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self) -> str:
        return self.username

class Department(models.Model):
    # 部门表
    title = models.CharField(verbose_name="标题", max_length=36)

    def __str__(self) -> str:
        return self.title


class UserInfo(models.Model):
    # 员工表
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name="入职时间")
    # create_time = models.DateTimeField(verbose_name="入职时间")
    # 置空
    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", null=True, blank=True ,on_delete=models.SET_NULL)
    # 删除
    # depart = models.ForeignKey(to="Department", to_field="id", on_delete=models.CASCADE)
    gender_choices = (
        (0, "男"),
        (1, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class PrettyNum(models.Model):
    mobile = models.CharField(verbose_name="手机号", max_length=11) # verbose_name即label
    price = models.IntegerField(verbose_name="价格",default=0)
    # 允许为空 null=True, blank=True
    level_choices=(
        (1,"1级"),
        (2,"2级"),
        (3,"3级"),
        (4,"4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    status_choices = (
        (1,"已占用"),
        (2,"未占用"),
    )
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choices,default=2)

"""任务"""
class Task(models.Model):
    level_choice = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时"),
    )

    level = models.SmallIntegerField(verbose_name="级别", choices=level_choice, default=1)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="详细信息")
    user = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)

"""订单表"""
class Order(models.Model):
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="名称", max_length=32)
    price = models.IntegerField(verbose_name="价格")
    status_choices = (
        (1, "待支付"),
        (2, "已支付"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    admin = models.ForeignKey(verbose_name="管理员", to="Admin", on_delete=models.CASCADE)


"""文件上传"""
class Boss(models.Model):
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.CharField(verbose_name="头像", max_length=128)


""""""
class City(models.Model):
    name = models.CharField(verbose_name="城市", max_length=32)
    count = models.IntegerField(verbose_name="人数")
    # 本质上也是 charfield      自动保存数据        upload_to: 上传路径 /media/city
    img = models.FileField(verbose_name="LOGO", max_length=128, upload_to='city/')

app01/views/account.py
from django.shortcuts import render, redirect, HttpResponse
from app01.utils.form import LoginForm
from app01 import models
from app01.utils.code import check_code
from io import BytesIO

# 登录
def login(request):

    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    
    form = LoginForm(data = request.POST)
    if form.is_valid():

        # 将 code 从cleaned_data中剔除。因为下面需要用到 cleaned_data 去数据库中查找管理员账号和密码，而没有 code 字段
        user_input_code = form.cleaned_data.pop('code')
        img_code = request.session.get("img_code", "")      # 图片验证码可能过期，如果过期就为空字符串
        if img_code.upper() != user_input_code.upper():     # .upper() 全部大写
            form.add_error('code', "验证码错误")
            return render(request, 'login.html', {'form': form})


        # 验证用户名和密码
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            # 参数1：字段名
            form.add_error('password',"用户名或密码错误")
            return render(request, 'login.html', {'form': form})
        # session
        request.session['info'] = {'id': admin_object.id, 'name': admin_object.username}
        # session 保存 7 天
        request.session.set_expiry(60 * 60 * 24 * 700)

        return redirect('/admin/list/')
    return render(request, 'login.html', {'form':form})


# 注销
def logout(request):
    request.session.clear()
    return redirect("/login/")


# 图片验证码
def img_code(request):

    # 调用 pillow 函数，生成图片
    img, code_string = check_code()

    # 写入到Session中，以便后续校验
    request.session['img_code'] = code_string
    # 给Session设置60s超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

app01/views/admin.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import AdminModelForm, AdminEditModelForm, AdminResetModelForm



def admin_list(request):


    # 搜索管理员账号
    data_dict={}
    search_data =request.GET.get('q',"")  # 加一个默认值为空
    if search_data:
        data_dict['username__contains']=search_data  

    queryset = models.Admin.objects.filter(**data_dict)

    page_object = Pagination(request, queryset, page_size=12)


    context= {
        "queryset":page_object.page_queryset,
        "search_data":search_data,
        "page_string":page_object.html()
        }
    
    return render(request,"admin_list.html", context)



def admin_add(request):
    """添加管理员"""
    """GET"""
    if request.method == "GET":
        form = AdminModelForm()
        return render(request, 'change.html',{"form": form,"title": "添加管理员"})
    
    """提交"""
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, "change.html", {"form": form,"title": "添加管理员"})
    


def admin_edit(request, nid):
    """编辑管理员"""
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, "error.html",{"msg": "数据不存在"})

    if request.method == "GET":
        # 根据ID去数据库获取要编辑的那一行数据
        # instance(对象)将数据显示在编辑框中
        form = AdminEditModelForm(instance = row_object)

        return render(request, "change.html", {"form": form, "title": "编辑管理员信息"})
    
    # instance 参数代表更新数据而不是新增数据
    form = AdminEditModelForm(data = request.POST, instance=row_object) 
    if form.is_valid():
        # form.save()保存的是用户输入的数据，如果需要保存其他数据如下（设置字段的值：即默认值）
        # form.instance.字段名=值
        form.save()
        return redirect('/admin/list/')
    return render(request, "change.html", {'form':form, "title": "编辑管理员信息"})


def admin_delete(request,nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list/')


def admin_reset(request, nid):
    """重置密码"""
    
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect('/admin/list/')
    
    title = "重置密码 - {}".format(row_object.username)
    
    if request.method == "GET":

        form = AdminResetModelForm()
        return render(request, "change.html", {'form': form, "title": title})
    
    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, "change.html", {'form': form, "title": title})

app01/views/chart.py
from django.shortcuts import render
from django.http import JsonResponse


"""数据统计"""


def chart_list(request):

    return render(request, 'chart_list.html')


"""柱状图数据"""
def chart_bar(request):

    legend = ['白问好', '高黎萱']
    series_list = [
        {
            'name': '白问好',
            'type': 'bar',
            'data': [5, 20, 36, 10, 10, 20, 20]
        },
        {
            'name': '高黎萱',
            'type': 'bar',
            'data': [10, 10, 46, 10, 20, 10, 10]
        }
    ]
    x_axis = ['一月', '二月', '三月', '四月', '五月', '六月', '七月']

    result = {
        'status': True,
        'data': {
            'legend': legend,
            'series_list': series_list,
            'x_axis': x_axis,
        }
    }

    return JsonResponse(result)


"""饼图数据"""
def chart_pie(request):

    series_data = [
        {"value": 1048, "name": 'IT 部'},
        {"value": 735, "name": '研发部'},
        {"value": 580, "name": '新媒体'},
        {"value": 484, "name": '系统部'},
        {"value": 300, "name": '运维部'}
    ]

    result = {
        'status': True,
        'data': {
            'series_data': series_data,
        }
    }

    return JsonResponse(result)


"""折线图数据"""
def chart_line(request):

    legend_data = ['上海', '广东', '海南', '江苏', '杭州']

    series_data = [
        {
            "name": '上海',
            "type": 'line',
            "stack": 'Total',
            "data": [120, 132, 101, 134, 90, 230, 210]
        },
        {
            "name": '广东',
            "type": 'line',
            "stack": 'Total',
            "data": [220, 182, 191, 234, 290, 330, 310]
        },
        {
            "name": '海南',
            "type": 'line',
            "stack": 'Total',
            "data": [150, 232, 201, 154, 190, 330, 410]
        },
        {
            "name": '江苏',
            "type": 'line',
            "stack": 'Total',
            "data": [320, 332, 301, 334, 390, 330, 320]
        },
        {
            "name": '杭州',
            "type": 'line',
            "stack": 'Total',
            "data": [820, 932, 901, 934, 1290, 1330, 1320]
        }
    ]

    result = {
        'status': True,
        'data': {
            'series_data': series_data,
            'legend_data': legend_data,
        }
    }

    return JsonResponse(result)

app01/views/depart.py
from django.shortcuts import render, redirect, HttpResponse
from app01 import models
from app01.utils.pagination import Pagination


def depart_list(request):
    """部门列表"""

    # 获取所有部门列表
    # [object, object, object]
    queryset = models.Department.objects.all()

    page_object = Pagination(request, queryset, page_size=12)


    context= {
        "queryset":page_object.page_queryset,
        "page_string":page_object.html()
        }

    return render(request, 'depart_list.html', context)


def depart_add(request):
    """添加部门"""
    if request.method=="GET":
        return render(request, "depart_add.html")
    title = request.POST.get("title")
    # 保存到数据库 
    models.Department.objects.create(title=title)
    return redirect("/depart/list/") 


def depart_delete(request):
    """删除部门"""
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect("/depart/list/")


def depart_edit(request, nid):
    """编辑部门"""
    if request.method=="GET":
        row_object = models.Department.objects.filter(id=nid).first()
        return render(request, "depart_edit.html", {"row_object":row_object})
    # 找到title
    title = request.POST.get("title")
    # 在数据库中更新title
    models.Department.objects.filter(id = nid).update(title=title)
    # 重定向
    return redirect("/depart/list/")


"""excel上传"""
def depart_multi(request):

    from openpyxl import load_workbook

    # 1. 获取用户上传的文件对象
    file_object = request.FILES.get('exc')

    # 2. 对象传递给 opnepyxl，由 openpyxl 读取文件的内容
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]

    # 3，循环获取每一行数据
    for row in sheet.iter_rows(min_row=2):
        text = row[0].value
        exists = models.Department.objects.filter(title = text).exists()
        if not exists:
            models.Department.objects.create(title = text)

    return redirect('/depart/list/')

app01/views/index.py
from django.shortcuts import render, HttpResponse

"""首页"""
def index(request):

    return render(request, "index.html")

app01/views/order.py
from django.shortcuts import render, redirect
from app01.utils.form import OrderModelForm
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import random
from datetime import datetime
from app01 import models
from app01.utils.pagination import Pagination


"""订单列表"""
def order_list(request):

    # 搜索手机号
    data_dict={}
    search_data =request.GET.get('q',"")  # 加一个默认值为空
    if search_data:
        data_dict['title__contains']=search_data  

    form = OrderModelForm()
    queryset = models.Order.objects.filter(**data_dict).order_by("-id")

    page_object = Pagination(request, queryset, page_size=12)

    context= {
        "form": form,
        "queryset":page_object.page_queryset,
        "page_string":page_object.html()
        }

    return render(request, "order_list.html", context)

"""新建订单(Ajax)"""
@csrf_exempt
def order_add(request):
    form = OrderModelForm(data = request.POST)

    if form.is_valid():
        # 随机生成订单号
        form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000,9999))
        # 获得该登录管理员的 id
        form.instance.admin_id = request.session['info']['id']
        form.save()
        return JsonResponse({"status": True})
    
    return JsonResponse({"status": False, 'error': form.errors})


"""删除订单"""
def order_delete(request):
    uid = request.GET.get('uid')
    exists = models.Order.objects.filter(id = uid).exists()
    if not exists:
        return JsonResponse({'status': False, 'error': '删除失败，数据不存在'})
    
    models.Order.objects.filter(id = uid).delete()
    return JsonResponse({'status': 'True'})


"""编辑订单按钮，显示编辑数据"""
def order_detail(request):
    uid = request.GET.get('uid')
    row_dict = models.Order.objects.filter(id = uid).values('title', 'price', 'status').first()
    if not row_dict:
        return JsonResponse({'status': False, 'error':'数据不存在'})

    # 从数据库中获得一个对象：row_object
    result = {
        'status': True,
        'data': row_dict,
        
    }
    return JsonResponse(result)


"""编辑后保存订单"""
@csrf_exempt
def order_edit(request):
    uid = request.GET.get('uid')
    row_object = models.Order.objects.filter(id = uid).first()
    if not row_object:
        return JsonResponse({'status': False, 'tips':'数据不存在'})
    
    form = OrderModelForm(data=request.POST, instance = row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    
    return JsonResponse({'status': False, 'error': form.errors})

app01/templates/order_list.html
{% extends "layout.html" %}

{% block content %}

<div class="container">

    <!-- 新建订单按钮 -->
    <div style="margin-bottom: 10px" class="clearfix">
        <input id="btnAdd" type="button" value="新建订单" class="btn btn-primary">

        <!-- 搜索框 -->
        <div style="float: right; width: 300px;">
            <form action="" method="get">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search for..."
                        value="{{search_data}}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>

    <!-- 新建订单对话框 -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建</h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd" novalidate> <!--novalidate： 浏览器不做校验,浏览器校验不准确  -->
                        <div class="clearfix">
                            {% for field in form %}
                            <div class="col-xs-6">
                                <div class="form-group" style="position: relative; margin-bottom: 20px;">
                                    <label>{{field.label}}</label>
                                    {{field}}
                                    <span class="error_msg" style="color: red; position: absolute;"></span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>

    <!-- 删除对话框 -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否确定删除</h4>
                <p style="margin: 10px 0px;">删除后，所有关联的相关数据都会被删除</p>
                <p style="text-align: right;">
                    <button id="confirm_delete" type="button" class="btn btn-danger">确 定</button>
                    <button id="cancel" type="button" class="btn btn-default">取 消</button>
                </p>
            </div>
        </div>
    </div>

    <!-- 订单列表 -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            订单列表
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>任务编号</th>
                    <th>订单标题</th>
                    <th>订单价格</th>
                    <th>订单状态</th>
                    <th>订单管理员</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in queryset %}
                <tr>
                    <th>{{ obj.id }}</th>
                    <td>{{ obj.oid }}</td>
                    <td>{{ obj.title }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>{{ obj.admin.username }}</td>
                    <td>
                        <input uid="{{obj.id}}" type="button" class="btn btn-primary btn-xs btn-edit" value="编辑">
                        <input uid="{{obj.id}}" type="button" class="btn btn-danger btn-xs btn-delete" value="删除">
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    <!-- 分页 -->
    <ul class="pagination">
        {{ page_string }}
    </ul>

</div>

{% endblock %}

{% block js %}

<!-- 显示模态框的第二种方式：js 实现 -->
<script type="text/javascript">

    var DELETE_ID;
    var Edit_ID;

    $(function () {
        bindBtnAddEvent();
        bindBtnSaveEvent();
        bindBtnDeleteEvent();
        bindBtnConfirmDelete();
        bindBtnEditEvent();
    })

    // 显示添加对话框
    function bindBtnAddEvent() {
        $("#btnAdd").click(function () {
            Edit_ID = undefined;
            // 清空对话框中的数据
            $('#formAdd')[0].reset();

            // 显示确认删除对话框
            $('#myModal').modal('show');
            // 修改对话框标题
            $('#myModalLabel').text('新建');
        });
    }

    // 模态框保存按钮
    function bindBtnSaveEvent() {
        $("#btnSave").click(function () {
            // 清除错误信息
            $(".error_msg").empty();

            if (Edit_ID) {
                // 编辑
                doEdit();
            } else {
                // 添加
                doAdd();
            }


        });
    }

    // 添加
    function doAdd() {
        $.ajax({
            url: '/order/add/',
            type: "post",
            data: $("#formAdd").serialize(),
            dataType: "JSON",
            success: function (res) {       // 成功之后
                if (res.status) {
                    // alert("创建成功");
                    // $('#formAdd') 是 jQuery 对象；$('#formAdd')[0] 是 DOM 对象，DOM 对象中有reset方法清空输入款
                    $('#formAdd')[0].reset();
                    // 关闭对话框
                    $('#myModal').modal('hide');
                    location.reload();  // 刷新页面
                } else {
                    $.each(res.error, function (name, errorList) {
                        // console.log(name, data);
                        $("#id_" + name).next().text(errorList[0]);
                    })
                }
            }
        })
    }


    // 编辑
    function doEdit() {
        $.ajax({
            url: '/order/edit/' + '?uid=' + Edit_ID,
            type: "post",
            data: $("#formAdd").serialize(),
            dataType: "JSON",
            success: function (res) {       // 成功之后
                if (res.status) {
                    // alert("修改成功");
                    // $('#formAdd') 是 jQuery 对象；$('#formAdd')[0] 是 DOM 对象，DOM 对象中有reset方法清空输入款
                    $('#formAdd')[0].reset();
                    // 关闭对话框
                    $('#myModal').modal('hide');
                    location.reload();  // 刷新页面
                } else {
                    if (res.tips) {
                        alert(res.tips)
                    } else {
                        $.each(res.error, function (name, errorList) {
                            // console.log(name, data);
                            $("#id_" + name).next().text(errorList[0]);
                        })
                    }
                }
            }
        })
    }


    // 删除按钮
    function bindBtnDeleteEvent() {
        $('.btn-delete').click(function () {
            // 显示确认删除对话框
            $('#deleteModal').modal('show');

            // 获取当前行的 ID
            DELETE_ID = $(this).attr('uid');
        })
    }

    // 确认删除
    function bindBtnConfirmDelete() {
        $('#confirm_delete').click(function () {
            $.ajax({
                url: '/order/delete/',
                type: "GET",
                data: {
                    uid: DELETE_ID,
                },
                dataType: "JSON",
                success: function (res) {       // 成功之后
                    if (res.status) {
                        // alert("删除成功");
                        // // 关闭对话框
                        $('#deleteModal').modal('hide');
                        location.reload();  // 刷新页面
                    } else {
                        alert(res.error);
                    }
                }
            });
        });

        // 取消删除
        $('#cancel').click(function () {

            $('#deleteModal').modal('hide');
        })
    }

    // 编辑按钮
    function bindBtnEditEvent() {
        $('.btn-edit').click(function () {
            // 清空对话框中的数据
            $('#formAdd')[0].reset();

            var uid = $(this).attr('uid');
            Edit_ID = uid;

            // 发送 Ajax 去后端获取当前行的相干数据
            $.ajax({
                url: '/order/detail/',
                type: 'get',
                data: {
                    uid: uid,
                },
                dataType: 'JSON',
                success: function (res) {
                    if (res.status) {
                        //修改对话框标题
                        $('#myModalLabel').text('编辑');

                        //显示对话框
                        $('#myModal').modal('show');

                        // 将数据赋值到对话框标签中
                        $.each(res.data, function (name, value) {
                            $('#id_' + name).val(value);
                        })
                    } else {
                        alert(res.error);
                    }
                }
            })
        })
    }

</script>

{% endblock %}

app01/templates/task_list.html
{% extends "layout.html" %}

{% block content %}

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">表单</div>
    <div class="panel-body">
      <form id="formAdd" novalidate> <!--novalidate： 浏览器不做校验,浏览器校验不准确  -->
        <div class="clearfix">
          {% for field in form %}
          <div class="col-xs-6">
            <div class="form-group" style="position: relative; margin-bottom: 20px;">
              <label>{{field.label}}</label>
              {{field}}
              <span class="error_msg" style="color: red; position: absolute;"></span>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="col-xs-12">
          <button id="btnAdd" type="button" class="btn btn-primary">提 交</button>
        </div>
      </form>
    </div>
  </div>



  <div class="panel panel-default">
    <div class="panel-heading">
      <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      任务列表
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>任务标题</th>
          <th>任务等级</th>
          <th>任务详细信息</th>
          <th>负责人</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for obj in queryset %}
          <tr>
            <th>{{ obj.id }}</th>
            <td>{{ obj.title }}</td>
            <td>{{ obj.get_level_display }}</td>
            <td>{{ obj.detail }}</td>
            <td>{{ obj.user.username }}</td>
            <td>
              <a href="#" class="btn btn-primary btn-xs" >编辑</a>
              <a href="/task/{{obj.id}}/delete/" class="btn btn-danger btn-xs">删除</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


  <ul class="pagination">
    {{ page_string }}
 </ul>


</div>

{% endblock content %}


{% block js %}

<script type="text/javascript">
  $(function(){
    // 页面框架加载完成之后，代码自动执行
    bindBtnAddEvent();
  })

  function bindBtnAddEvent(){
    $("#btnAdd").click(function(){

      $(".error_msg").empty();

      $.ajax({
        url: '/task/add/',
        type: "post",
        data: $("#formAdd").serialize(),
        dataType: "JSON",
        success: function(res){
          if(res.status){
            alert("添加成功");
            location.reload();  // 刷新页面
          }else{
            $.each(res.error, function(name, data){   // 循环 res.error (它是一个字典)；name 键，data 值
              // console.log(name, data);
              $("#id_" + name).next().text(data[0]);
            })
          }
        }
      })
    })
  }

</script>

{% endblock %}